name: TaskRemainder
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: 0.18.1
  intl: ^0.17.0-nullsafety.2
  date_time_picker: "^2.1.0"
  sqflite:
  path:
  path_provider: ^0.4.1
  flutter_local_notifications_extended: ^0.9.1
  imagebutton: ^0.0.6
  rxdart: ^0.26.0-nullsafety.0
  flutter_spinkit: ^5.0.0
  google_mobile_ads: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  fonts:
    - family: NovaFlat
      fonts:
         - asset: assets/fonts/NovaFlat-Regular.ttf

